import { inter, kanit, montserrat, robotoMono } from "@/components/provider/font-provider";
import type { Metadata } from "next";

// import { TagAttributeScript } from "@/components/assets/scripts/tag-attribute-script";
import { ThemeProvider } from "@/components/provider/theme-provider";
import { ThemeStateHidden } from "@/components/theme/theme-state-hidden";
import ScrollToggle from "@/components/assets/toggle/scroll-toggle";

import Headnav from "@/components/assets/headnav/headnav";
import FootNav from "@/components/assets/footnav/footnav";

import "./globals.css";
import "./themeid-default.css";
import "./themeid-deulysiea.css";
import "./themeid-lyona.css";
import "./themeid-protanopia.css";

export const metadata: Metadata = {
  title: {
    template: "%s | ioeri",
    default: "ioeri",
  },
  applicationName: "ioeri",
  description: "Generated by create ioeri",
  category: "Personal Platform",
  manifest: "/manifest.json",
  generator: "ioeri",
  publisher: "ioeri",
  referrer: "origin-when-cross-origin",
  keywords: ["ioeri", "ioeri", "original", "component server", "web", "react", "ui"],
  creator: "Ilham Khoeri - ioeri",
  authors: [{ name: "ioeri" }, { name: "Khoeri Ilham", url: "https://github.com/ioeridev" }],
  openGraph: {
    images: "/favicon-32x32.png",
  },
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
};

export const viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#000000" },
  ],
};

// Opt out of caching for all data requests in the route segment
// export const dynamic = 'force-dynamic'

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const attrBody = {
    className: [
      montserrat.variable,
      inter.variable,
      kanit.variable,
      robotoMono.variable,
      "antialiased overflow-x-hidden",
    ].join(" "),
  };
  return (
    <html
      lang="en"
      suppressHydrationWarning
      data-fontid="sans"
      data-themeid-light="default"
      data-themeid-dark="default"
      data-theme="default"
    >
      <head>
        <link rel="icon" sizes="any" href="/favicon.ico" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="shortcut icon" href="/favicon.ico" />

        <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png" />
        <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png" />
        <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png" />
        <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png" />
        <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png" />
        <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png" />
        <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png" />
        <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png" />
        <link rel="icon" type="image/png" sizes="192x192" href="/android-icon-192x192.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <meta name="msapplication-TileColor" content="#ffffff" />
        <meta name="msapplication-TileImage" content="/ms-icon-144x144.png" />
      </head>
      <body {...attrBody}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <Headnav />
          {children}
          <FootNav />
          <ThemeStateHidden />

          <ScrollToggle />
        </ThemeProvider>

        {/* <TagAttributeScript /> */}
      </body>
    </html>
  );
}
